[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"

[functions]
directory = "netlify/functions"

# SPA fallback (React Router)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
