[build]
command = "npm run build"
publish = "dist"
# If there are no changes outside excluded paths, 'git diff --quiet' exits 0 → Netlify skips the build
# Excluded paths: docs/**, .github/**, CODEOWNERS
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)docs/**' ':(exclude).github/**' ':(exclude)CODEOWNERS'"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers applied only in production context (keeps deploy previews open)
[context.production]

	[[context.production.headers]]
	for = "/advisor"
		[context.production.headers.values]
		Basic-Auth = "advisor:REDACTED"         # rotate in Netlify UI after commit
		X-Robots-Tag = "noindex, nofollow"
		Cache-Control = "no-store"

	[[context.production.headers]]
	for = "/advisor/*"
		[context.production.headers.values]
		Basic-Auth = "advisor:REDACTED"
		X-Robots-Tag = "noindex, nofollow"
		Cache-Control = "no-store"
